### ISSUE TITLE
Autogenerate secret.key on first start

### ISSUE THREAD

**Issue by domenkozar** [hercules-ci/hercules#19]
cc @expipiplus1

**Comment by expipiplus1** [comment]
Seems pretty reasonable.

I suppose hercules should write to the filename given by the user iff it doesn't exist and there is nothing encrypted with any key so far.

**Comment by expipiplus1** [comment]
If there is data encrypted with a key and no key is provided we should terminate with an error. 

If there is data encrypted with a different key, the same.

We'll need to store the hash of the key or something so we can verify that it's the same one.

**Comment by domenkozar** [comment]
I wouldn't go as far. Ff there is encrypted data, the key should exist and app will try to use it. Otherwise it's too many knobs in that logic.

**Comment by expipiplus1** [comment]
I think it's better to check if the key is valid than fail to authenticate with github later on

**Comment by domenkozar** [comment]
Agreed, but I'd leave that for 0.2 or later since it's a very edge case.

**Comment by BunsenMcDubbs** [comment]
This seems to have been fixed already in #24 Is that correct?

**Comment by expipiplus1** [comment]
Correct!
