### ISSUE TITLE
Backend API Documentation

### ISSUE THREAD

**Issue by domenkozar** [hercules-ci/hercules#2]
I propose we use Rst/Sphinx and thus https://readthedocs.org/ for hosting docs.

- export the Servant API to RST by implementing servant-httpdomain package using https://pythonhosted.org/sphinxcontrib-httpdomain/#basic-usage

- serve servant-swagger on `/`

cc @expipiplus1

**Comment by expipiplus1** [comment]
Anything that can be automatically generated from the source is fine by me :)

**Comment by expipiplus1** [comment]
`servant-pandoc` seems to be a little outdated and doesn't support some of the constructs created by `servant-doc` such as the authentication section.

Here's an example of the rst documentation generated https://gist.github.com/expipiplus1/2199b4d8bcac877482780be8a7fd6fef

**Comment by jkarni** [comment]
You might want to consider `servant-swagger` instead. You can then have a documentation page like [this](http://petstore.swagger.io/#/) automatically, and there's more tooling around the `swagger` format then the custom markdown format `servant-doc` generates.

**Comment by domenkozar** [comment]
I was thinking about that. Could we still generate a static page out of the swagger json file?

**Comment by jkarni** [comment]
Static in the sense of no javascript, or in the sense of no server? If the latter, then yes (`swagger-ui` just parses the json file); if the former, that'd be a bit harder.

**Comment by domenkozar** [comment]
Something that can be included into docs, so that users can read api specs without running the server. We'll probably use swagger and rst, just because we can :-)

**Comment by domenkozar** [comment]
Alternative to pandoc might be https://pythonhosted.org/sphinxcontrib-httpdomain/ 

Example docs: http://trolasi.readthedocs.io/en/latest/

But we'd have to write our own integration to generate that.

**Comment by domenkozar** [comment]
I've updated this issue with clearer goals.

**Comment by domenkozar** [comment]
Definitely need httpdomain support, this is pretty terrible: http://hercules-ci.s3-website-us-west-2.amazonaws.com/api.html

**Comment by dmjio** [comment]
re: `servant-swagger`, this project makes it even easier to host a swagger-ui site, along-side the web server. https://github.com/phadej/servant-swagger-ui#readme

**Comment by domenkozar** [comment]
I've started some work on `servant-docs` to add https://pythonhosted.org/sphinxcontrib-httpdomain/ formatting support. Very WIP, hope to get some time by end of the week to get it done :)

**Comment by domenkozar** [comment]
I still need to add `servant-swagger-ui`, but the static version is ready: https://github.com/hercules-ci/hercules/pull/35

**Comment by domenkozar** [comment]
Implemented in #35 we have generated docs at http://hercules-ci.s3-website-us-west-2.amazonaws.com/api.html and swagger ui served at /
