### ISSUE TITLE
What's the license?

### ISSUE THREAD

**Issue by angerman** [hercules-ci/hercules#8]
I could not determine the license this code is under, could this be resolved?

**Comment by expipiplus1** [comment]
Both the backend and frontend are BSD3 licensed. 

https://github.com/hercules-ci/hercules/blob/master/backend/LICENSE

https://github.com/hercules-ci/hercules/blob/master/frontend/elm-package.json

Perhaps this information should be in the root directory.

**Comment by angerman** [comment]
@expipiplus1 Thanks.
